// Define the fields for interior and exterior dynamically
export const interiorFields = [
  { name: "Office/Study", key: "officeStudy" },
  { name: "Living Room", key: "livingRoom" },
  { name: "Entry", key: "entry" },
  { name: "Hallway", key: "hallway" },
  { name: "Kitchen", key: "kitchen" },
  { name: "Master Bed", key: "masterBed" },
  { name: "Master Bath", key: "masterBath" },
  { name: "Bedroom A", key: "bedroomA" },
  { name: "Bathroom A", key: "bathroomA" },
  { name: "Bedroom B", key: "bedroomB" },
  { name: "Bathroom B", key: "bathroomB" },
  { name: "Bedroom C", key: "bedroomC" },
  { name: "Laundry Room", key: "LaundryRoom" },
  { name: "Basement", key: "Basement" },
  { name: "Repair", key: "Repair" },
  { name: "Dry Wall", key: "DryWall" },
  { name: "Built-In Book Shelves", key: "BuiltInBookShelves" },
  { name: "Powder Bathroom", key: "PowderBathroom" },
];

export const exteriorFields = [
  { name: "Body Siding", key: "bodySiding" },
  { name: "Trim", key: "trim" },
  { name: "Facial", key: "facial" },
  { name: "Soffits", key: "soffits" },
  { name: "Shutters", key: "shutters" },
  { name: "Gutters", key: "gutters" },
  { name: "Front Door", key: "frontDoor" },
  { name: "Garage Door", key: "garageDoor" },
  { name: "Fence", key: "fence" },
  { name: "Deck", key: "deck" },
  { name: "Porch", key: "porch" },
  { name: "Pergola", key: "pergola" },
  { name: "Foundation", key: "Foundation" },
  { name: "Shed", key: "Shed" },
  { name: "Stucco", key: "Stucco" },
  { name: "Bricks", key: "Bricks" },
  { name: "Replace Garage Weather Strip", key: "ReplaceGarageWeatherStrip" },
];
